### ISSUE TITLE
Trouble building theme with newest version

### ISSUE THREAD

**Issue by joranb** [timofei-iatsenko/keycloakify-emails#7]
Whenever trying to build a theme with a newer version of keycloakify than the one in the example I get this error:

```
 npm run build-keycloak-theme

> keycloakify-starter@0.0.0 build-keycloak-theme
> pnpm build && keycloakify build


> keycloakify-starter@0.0.0 build /home/joranb/ov/keycloak-theme
> tsc && vite build

vite v5.4.11 building for production...

/src/fonts/Roboto-Regular.ttf referenced in /src/fonts/Roboto-Regular.ttf didn't resolve at build time, it will remain unchanged to be resolved at runtime

/src/fonts/Roboto-Bold.ttf referenced in /src/fonts/Roboto-Bold.ttf didn't resolve at build time, it will remain unchanged to be resolved at runtime

/src/fonts/Montserrat-Bold.ttf referenced in /src/fonts/Montserrat-Bold.ttf didn't resolve at build time, it will remain unchanged to be resolved at runtime
✓ 168 modules transformed.
dist/index.html                                                 0.36 kB │ gzip:  0.25 kB
dist/assets/arrow-back-Dk_9AwXy.css                             0.46 kB │ gzip:  0.26 kB
dist/assets/KcPage-CEl_1_Hy.css                                 1.46 kB │ gzip:  0.58 kB
dist/assets/waitForElementMountedOnDom-qpCjLZnq.js              0.26 kB │ gzip:  0.22 kB
dist/assets/LoginPageExpired-CxbwkIRh.js                        0.65 kB │ gzip:  0.35 kB
dist/assets/Error-DlmCb-3I.js                                   0.67 kB │ gzip:  0.41 kB
dist/assets/LoginVerifyEmail-rA61SZ3y.js                        0.69 kB │ gzip:  0.39 kB
dist/assets/Code-zlB6cA7G.js                                    0.72 kB │ gzip:  0.42 kB
dist/assets/FrontchannelLogout-BsrE8Nn8.js                      0.80 kB │ gzip:  0.45 kB
dist/assets/LoginIdpLinkEmail-Bwpb0eZY.js                       0.87 kB │ gzip:  0.37 kB
dist/assets/LoginIdpLinkConfirmOverride-TylGbhT_.js             0.91 kB │ gzip:  0.48 kB
dist/assets/Terms-Df4ejcdX.js                                   0.95 kB │ gzip:  0.46 kB
dist/assets/DeleteCredential-BbIPYRWF.js                        0.98 kB │ gzip:  0.49 kB
dist/assets/SamlPostForm-DpbGq-Yo.js                            1.03 kB │ gzip:  0.52 kB
dist/assets/LoginIdpLinkConfirm-Ccfa-ROp.js                     1.05 kB │ gzip:  0.46 kB
dist/assets/Info-9XxTO4W9.js                                    1.09 kB │ gzip:  0.56 kB
dist/assets/IdpReviewUserProfile-DrLSrsRW.js                    1.27 kB │ gzip:  0.60 kB
dist/assets/arrow-back-CgKpWwUJ.js                              1.29 kB │ gzip:  0.76 kB
dist/assets/LogoutConfirm-CXIGDDvG.js                           1.43 kB │ gzip:  0.61 kB
dist/assets/WebauthnError-BnwJC8qx.js                           1.45 kB │ gzip:  0.65 kB
dist/assets/DeleteAccountConfirm-sn03k1qL.js                    1.47 kB │ gzip:  0.69 kB
dist/assets/LoginUpdateProfile-DJt-1UBl.js                      1.48 kB │ gzip:  0.67 kB
dist/assets/SelectAuthenticator-qbecQSdZ.js                     1.50 kB │ gzip:  0.56 kB
dist/assets/LoginOauth2DeviceVerifyUserCode-Dgnyh0Pq.js         1.59 kB │ gzip:  0.58 kB
dist/assets/LoginRecoveryAuthnCodeInput-DPxw7ZUE.js             1.91 kB │ gzip:  0.74 kB
dist/assets/LoginResetOtp-BJrUrlfF.js                           1.92 kB │ gzip:  0.74 kB
dist/assets/UpdateEmail-Ba_-oFcv.js                             1.94 kB │ gzip:  0.77 kB
dist/assets/LoginResetPassword-BbGc1lrJ.js                      1.99 kB │ gzip:  0.94 kB
dist/assets/LoginResetPassword-CuHvis09.js                      2.12 kB │ gzip:  0.84 kB
dist/assets/LoginOauthGrant-B-OMSqVn.js                         2.34 kB │ gzip:  0.83 kB
dist/assets/LoginX509Info-CWXmoYOw.js                           2.43 kB │ gzip:  0.66 kB
dist/assets/LoginOtp-CoqnANhW.js                                2.64 kB │ gzip:  0.91 kB
dist/assets/LoginPassword-JXanT_fz.js                           2.65 kB │ gzip:  1.06 kB
dist/assets/LoginUsername-_gf7qQ8R.js                           3.33 kB │ gzip:  1.25 kB
dist/assets/Register-BUMqORCm.js                                3.47 kB │ gzip:  1.19 kB
dist/assets/LoginUpdatePassword-U08VAROB.js                     3.56 kB │ gzip:  1.11 kB
dist/assets/LoginUpdatePassword-CbRSX9sM.js                     3.90 kB │ gzip:  1.15 kB
dist/assets/WebauthnRegister-D8UGFeP1.js                        4.32 kB │ gzip:  1.47 kB
dist/assets/WebauthnAuthenticate-yJJj7vY4.js                    4.92 kB │ gzip:  1.66 kB
dist/assets/Login-DGtXvLGD.js                                   5.11 kB │ gzip:  1.70 kB
dist/assets/LoginConfigTotp-C3wHIbPb.js                         5.14 kB │ gzip:  1.41 kB
dist/assets/LoginPasskeysConditionalAuthenticate-bXgZx3-Y.js    6.16 kB │ gzip:  2.01 kB
dist/assets/Login-UbHn_tKP.js                                   7.11 kB │ gzip:  2.46 kB
dist/assets/LoginRecoveryAuthnCodeConfig-B_2HKfKt.js           10.08 kB │ gzip:  2.45 kB
dist/assets/lv-COGRecan.js                                     10.23 kB │ gzip:  3.81 kB
dist/assets/no-BLSeCS6i.js                                     11.35 kB │ gzip:  3.77 kB
dist/assets/sv-gxsZPHzM.js                                     11.53 kB │ gzip:  3.91 kB
dist/assets/lt-lcQwb6Kg.js                                     11.59 kB │ gzip:  4.03 kB
dist/assets/ru-D1G0AjUs.js                                     12.62 kB │ gzip:  5.19 kB
dist/assets/ja-DaTmYLEp.js                                     13.47 kB │ gzip:  6.52 kB
dist/assets/tr-DJYkfU6S.js                                     14.58 kB │ gzip:  5.21 kB
dist/assets/nl-8d7VZNr1.js                                     16.00 kB │ gzip:  5.18 kB
dist/assets/pl-DrMiAMGV.js                                     16.18 kB │ gzip:  5.67 kB
dist/assets/zh-CN-B-8Z8uCe.js                                  16.19 kB │ gzip:  8.43 kB
dist/assets/zh-TW-BZiMTvQs.js                                  16.74 kB │ gzip:  8.52 kB
dist/assets/da-B74hwG9_.js                                     17.72 kB │ gzip:  5.68 kB
dist/assets/it-CJA8pkPG.js                                     18.51 kB │ gzip:  5.74 kB
dist/assets/pt-BR-D9XZcV46.js                                  20.65 kB │ gzip:  6.53 kB
dist/assets/fi-pyiGp8E_.js                                     22.36 kB │ gzip:  7.23 kB
dist/assets/fa-0nysJ_Sw.js                                     24.67 kB │ gzip:  8.98 kB
dist/assets/fr-DJQgrVMW.js                                     24.74 kB │ gzip:  7.33 kB
dist/assets/th-BeXV8m3U.js                                     24.92 kB │ gzip:  9.11 kB
dist/assets/ar-Wj68h1dE.js                                     25.27 kB │ gzip:  9.11 kB
dist/assets/cs-D2gGu2W7.js                                     25.89 kB │ gzip:  8.79 kB
dist/assets/sk-BiB-tlch.js                                     26.88 kB │ gzip:  9.08 kB
dist/assets/UserProfileFormFields-BuIRvdvp.js                  27.17 kB │ gzip:  7.38 kB
dist/assets/el-b3nB1eyb.js                                     27.42 kB │ gzip:  9.93 kB
dist/assets/uk-BaKI4Lg2.js                                     27.83 kB │ gzip:  9.87 kB
dist/assets/pt-DI6Oi4SA.js                                     28.00 kB │ gzip:  8.35 kB
dist/assets/hu-DWlA5Y0t.js                                     28.31 kB │ gzip:  8.98 kB
dist/assets/ka-DHVLHruY.js                                     28.41 kB │ gzip: 10.51 kB
dist/assets/ca-v3rdJ2Kh.js                                     28.55 kB │ gzip:  8.36 kB
dist/assets/es-CektV-lJ.js                                     29.19 kB │ gzip:  8.90 kB
dist/assets/de-7MuTqd-5.js                                     30.20 kB │ gzip:  9.03 kB
dist/assets/KcPage-C0ptlkUE.js                                 93.16 kB │ gzip: 29.93 kB
dist/assets/index-Ae7nRvOj.js                                 143.97 kB │ gzip: 46.51 kB
✓ built in 837ms
keycloakify v11.5.3 Building the keycloak theme in ./dist_keycloak ...
error when starting dev server:
Error: Cannot find package 'undefined' imported from /home/joranb/ov/keycloak-theme/node_modules/.pnpm/keycloakify-emails@2.0.1_jsx-email@2.5.4_react@18.3.1/node_modules/keycloakify-emails/dist/index.mjs
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:146:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:176:14)
    at buildEmailTheme (file:///home/joranb/ov/keycloak-theme/node_modules/.pnpm/keycloakify-emails@2.0.1_jsx-email@2.5.4_react@18.3.1/node_modules/keycloakify-emails/dist/index.mjs:137:46)
Error: Command failed: npx vite
error when starting dev server:
Error: Cannot find package 'undefined' imported from /home/joranb/ov/keycloak-theme/node_modules/.pnpm/keycloakify-emails@2.0.1_jsx-email@2.5.4_react@18.3.1/node_modules/keycloakify-emails/dist/index.mjs
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:146:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:176:14)
    at buildEmailTheme (file:///home/joranb/ov/keycloak-theme/node_modules/.pnpm/keycloakify-emails@2.0.1_jsx-email@2.5.4_react@18.3.1/node_modules/keycloakify-emails/dist/index.mjs:137:46)

    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at command (/home/joranb/ov/keycloak-theme/node_modules/.pnpm/keycloakify@11.5.3/node_modules/keycloakify/bin/573.index.js:1514:33)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async handler (/home/joranb/ov/keycloak-theme/node_modules/.pnpm/keycloakify@11.5.3/node_modules/keycloakify/bin/main.js:16157:9)
    at async /home/joranb/ov/keycloak-theme/node_modules/.pnpm/keycloakify@11.5.3/node_modules/keycloakify/bin/main.js:15349:1145
    at async /home/joranb/ov/keycloak-theme/node_modules/.pnpm/keycloakify@11.5.3/node_modules/keycloakify/bin/main.js:15349:2646 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 42 75 69 6c 64 20 65 6d 61 69 6c 73 20 66 6f 72 20 63 75 73 74 6f 6d 20 74 68 65 6d 65 73 0a 44 69 73 63 6f 76 65 72 65 64 20 74 65 6d 70 6c 61 74 65 ... 3 more bytes>,
    <Buffer 65 72 72 6f 72 20 77 68 65 6e 20 73 74 61 72 74 69 6e 67 20 64 65 76 20 73 65 72 76 65 72 3a 0a 45 72 72 6f 72 3a 20 43 61 6e 6e 6f 74 20 66 69 6e 64 ... 1019 more bytes>
  ],
  pid: 146738,
  stdout: <Buffer 42 75 69 6c 64 20 65 6d 61 69 6c 73 20 66 6f 72 20 63 75 73 74 6f 6d 20 74 68 65 6d 65 73 0a 44 69 73 63 6f 76 65 72 65 64 20 74 65 6d 70 6c 61 74 65 ... 3 more bytes>,
  stderr: <Buffer 65 72 72 6f 72 20 77 68 65 6e 20 73 74 61 72 74 69 6e 67 20 64 65 76 20 73 65 72 76 65 72 3a 0a 45 72 72 6f 72 3a 20 43 61 6e 6e 6f 74 20 66 69 6e 64 ... 1019 more bytes>
}
```

Using that old version however does not play well with Keycloak 26.0.7, I can install the theme but then the Keycloak login screen is blank and has this error in the console: 
DOMException: String contains an invalid character

package.json:

```
{
  "name": "keycloakify-starter",
  "version": "0.0.0",
  "description": "Starter for Keycloakify 11",
  "repository": {
    "type": "git",
    "url": "git://github.com/codegouvfr/keycloakify-starter.git"
  },
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "build-keycloak-theme": "pnpm build && keycloakify build",
    "storybook": "storybook dev -p 6006",
    "format": "prettier . --write",
    "emails:check": "email check ./emails/templates",
    "emails:preview": "email preview ./emails/templates"
  },
  "license": "MIT",
  "keywords": [],
  "dependencies": {
    "keycloakify": "^11.5.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@eslint/js": "^9.15.0",
    "@storybook/react": "^8.1.10",
    "@storybook/react-vite": "^8.1.10",
    "@types/node": "^22.9.1",
    "@types/react": "^18.2.43",
    "@types/react-dom": "^18.2.17",
    "@typescript-eslint/eslint-plugin": "^8.15.0",
    "@typescript-eslint/parser": "^8.15.0",
    "@vitejs/plugin-react": "^4.2.1",
    "esbuild": "^0.24.0",
    "eslint": "^9.15.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-react": "^7.37.2",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.14",
    "eslint-plugin-storybook": "^0.11.1",
    "globals": "^15.12.0",
    "jsx-email": "^2.5.4",
    "keycloakify-emails": "^2.0.1",
    "prettier": "3.3.1",
    "storybook": "^8.1.10",
    "typescript": "^5.2.2",
    "typescript-eslint": "^8.15.0",
    "vite": "^5.0.8"
  },
  "engines": {
    "node": "^18.0.0 || >=20.0.0"
  },
  "packageManager": "pnpm@9.14.2+sha512.6e2baf77d06b9362294152c851c4f278ede37ab1eba3a55fda317a4a17b209f4dbb973fb250a77abc463a341fcb1f17f17cfa24091c4eb319cda0d9b84278387"
}

```

vite.config.ts:

```
// vite.config.ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";
import { buildEmailTheme } from "keycloakify-emails";

export default defineConfig({
  plugins: [
    react(),
    keycloakify({
      accountThemeImplementation: "none",
      themeName: ["custom"],
      keycloakVersionTargets: {
        "22-to-25": false,
        "all-other-versions": "overvinne-theme.jar"
      },
      postBuild: async (buildContext) => {
        const { config: loadConfig } = await import("./jsx-email.config.js");

        const config = await loadConfig;

        await buildEmailTheme({
          templatesSrcDirPath: import.meta.dirname + "/emails/templates",
          i18nSourceFile: import.meta.dirname + "/emails/i18n.ts",
          themeNames: buildContext.themeNames,
          keycloakifyBuildDirPath: buildContext.keycloakifyBuildDirPath,
          locales: ["en", "no"],
          esbuild: config.esbuild,
          cwd: import.meta.dirname,
        });
      }

    })
  ]
});
```

The theme worked fine before installing keycloakify-emails. Seems like an issue with importing the path to the i18nFileModule. This line is the culprit:

`  const i18nFileModule = await import(bundled[path.resolve(opts.cwd, opts.i18nSourceFile)]);`

I ran it on Ubuntu 24 btw.

**Comment by timofei-iatsenko** [comment]
Yes, i also noticesd this, please stick to the previous one until i'll find a solution.

**Comment by timofei-iatsenko** [comment]
Fixed in https://github.com/timofei-iatsenko/keycloakify-emails/releases/tag/2.0.2

Turned out that when it called from keycloackify the CWD is different, and it creates all sort of problems. This was not caught by the tests because they running the lib in isolation. I added more tests to prevent such issue in the future. Sorry for inconvenience.

**Comment by joranb** [comment]
@timofei-iatsenko 

Thank you for the quick fix. Now it builds just fine, I do however have a problem. The npm run build-keycloak-theme succeeds just fine and I copy my jar into the docker image for building, login theme works great, but for email I get this error in Keycloak log for my theme named custom:

ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-3) Failed to find EMAIL theme custom, using built-in themes 

So I keep getting the built-in theme. 

I attached my project, probably missed something. Would really appreciate it if you could take a quick look. 


[keycloakify-emails-repo.zip](https://github.com/user-attachments/files/18209114/keycloakify-emails-repo.zip)

**Comment by timofei-iatsenko** [comment]
@joranb i don't know why in particular it doesn't work in your case. I checked the code and doesn't see anything suspicious.  I suggest you to run a local KC instance with `keycloakify start-keycloak` and simulate an action causing an email (eq password reset request) 

The directory structure is good:

<img width="430" alt="image" src="https://github.com/user-attachments/assets/36fb80d6-7d32-4c85-b0fc-c948172c32a7" />


Try to remove everything from the template and i18n.ts file until it start working and then bring back functionality one by one. 

One more thing, i noticed that you use i18n.ts file for translation which is used in jsx generation only. The i18n file was mode for a different purpose, it was made to override properties in the `messages_en.properties` which are not presented in the email bodies. So whatever you will write in the i18n.ts would be serialized into properties files.  And if there would be errors, it can affect theme loading. 

In my case i'm using JSX-email with lingui, which is giving much more pleasant user experience in terms of i18n. But you can choose whatever solution you'd like. Even just create a separate file with the same logic as in i18n.ts, just to be sure messages used for pre-generation are not mixed up with messages used by KC runtime.

**Comment by timofei-iatsenko** [comment]
I've just launched local keyclock with your theme and see this 

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/3bfc0dda-305b-4bde-9369-34de73136eac" />

(it shouldn't show "custom attribute...", should show "custom")

I think name "custom" is somehow clashing with somethin in the KC, might be worth to rename it and try again.

**Comment by timofei-iatsenko** [comment]
I renamed the theme (just removed themeNames from vite config) and sucefully received styled email:

<img width="687" alt="image" src="https://github.com/user-attachments/assets/8a06f560-9d12-4799-b1d5-4f306648f604" />

**Comment by joranb** [comment]
@timofei-iatsenko 

Thank you for your help debugging this. That is the excuse I needed to change the theme name, I know naming is hard, but was not very pleased with our developers name choice of "custom". He left us a while ago, I hoped I never had to learn theming in Keycloak, but Keycloak 26 changed that (our theme crashed when upgrading from 25->26). I kept the name simply because changing it to something more descriptive would require me to update all clients that use this theme with the new theme name. 

Have to work a bit more with the email I see, the horizontal alignment of social icons was not quite on point. Again, thank you for this, and for this amazing library. Hopefully I am done bothering you now. :)

**Comment by timofei-iatsenko** [comment]
@joranb worth mentioning that i haven't tried sending a email with kc 26 nor with an older theme name. So my conclusions could be wrong.  I'm always starting 25 version (it's just a physical memory, we use 25 at our company), and noticed incorrect name, I renamed it straight away and tested sending.  So please re-check it by your own.
